### ISSUE TITLE
RFC: Providing options to filters

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-filters#14]
As it stands, some filters accept positional arguments, while some accept an options object. Is this inconsistency okay?

For reference, Nunjuck’s own built in filters use positional arguments, i.e. [the sort filter](https://mozilla.github.io/nunjucks/templating.html#sort-arr-reverse-casesens-attr):

```njk
{{ items | sort(true, true, "title") }}
```

## Filters with positional arguments

* `formatList(type)`
* `rejectFromArray(key, value)`
* `selectFromArray(key, value)`
* `duration(number, unit)`
* `govukDate(truncate)`
* `isoDateFromDateInput(namePrefix)`
* `monthName(truncate)`
* `sterling(trailingZeroIfInteger)`
* `startsWith(value)`

## Filters with options object

* `govukMarkdown({ headingsStartWith, smartypants })`

## Filters with positional arguments and options object

* `pluralise(singular, { plural, number })`

* * *

Positional arguments can be opaque in usage, and require a MAJOR release if the order is changed. However, they allow for terser code and can sometimes be quite readable, for example `{{ date | duration(5, "days") }}`. However, if you want to change the third argument, you need to provide values for the other proceeding 2. This can sometimes be avoided with sensible ordering, but gets harder the more options are provided.

Options objects are more verbose, but it's clearer which options have been set, for example `{{ text | govukMarkdown({ headingsStartWith "xl" }) }}`, and options can be set independently of others. New options can be added without a MAJOR release, but that being said, filters shouldn’t be overburdened with options anyway.

Questions:

1. Most filters use positional options, which is consistent with Nunjucks. Should the filters that don’t use this pattern be refactored to use positional arguments?

2. Is `pluralise` a good pattern to follow, using positional for common options, and an options object for finer grain control?

3. Do we need some rules around when to use an options object over positional arguments?

Be good to decide on an approach and any changes before releasing v1.0, which of course is a MAJOR release.

**Comment by frankieroberto** [comment]
I tend to think that positional arguments should be avoided unless it’s truly obvious what the argument means - which is normally only the case when there’s a single argument which isn’t true/false, like `startsWith`.

On the other hand the options object can also be confusing - although it is at least consistent with govuk-frontend. I’m not entirely sure why the design system team chose to always do it this way.

A third option is keyword arguments: https://mozilla.github.io/nunjucks/api#keyword-default-arguments but they seem to be rarely used in nunjucks?

**Comment by paulrobertlloyd** [comment]
> A third option is keyword arguments

Oh interesting, I hadn’t spotted that. This seems like a good middle, and one which also follows existing Nunjucks conventions.

In which case, maybe its a case of updating the 2 filters that use objects to use keyword arguments instead:

* `govukMarkdown(kwargs) // kqargs.headingsStartWith, kqargs.smartypants`, for example:

  ```njk
  {{ markdown | govukMarkdown(headingsStartWith="xl", smartypants=false) }}
  ```

* `pluralise(singular, kwargs) // kwargs.plural, kwargs.showCount`, for example:


  ```njk
  {{ 2 | pluralise('mouse', plural="mice", showCount=false) }}
  ```

**Comment by frankieroberto** [comment]
> In which case, maybe its a case of updating the 2 filters that use objects to use keyword arguments instead:
> 
> * `govukMarkdown(kwargs) // kqargs.headingsStartWith, kqargs.smartypants`, for example:
>   ```
>   {{ markdown | govukMarkdown(headingsStartWith="xl", smartypants=false) }}
>   ```

I like this - seems nice and readable?

> * `pluralise(singular, kwargs) // kwargs.plural, kwargs.showCount`, for example:
>   ```
>   {{ 2 | pluralise('mouse', plural="mice", showCount=false) }}
>   ```

This one took me a bit longer to parse, I think because "pluralising" a number is not how you'd regularly describe it? Would it make sense to reverse the arguments?

```nunjucks
{{ "mouse" | pluralise(2, plural="mice", showCount=false) }}
```

Possibly at that point it makes sense to label all the arguments:

```nunjucks
{{ "mouse" | pluralise(count=2, plural="mice", showCount=false) }}
```

It's a different language, but the [Swift argument labels style guide](https://www.swift.org/documentation/api-design-guidelines/#argument-labels) suggests always labelling arguments except in a few cases where it's already super obvious – and I think that's a good rule of thumb?

**Comment by frankieroberto** [comment]
For `selectFromArray` and `rejectFromArray`, I wonder if it'd make sense to accept an object, so that you could specify multiple keys and values?

```
{{ [{
  name: "Sally Smith",
  age: 30,
  role: "admin"
}, {
  name: "David Jones",
  age: 30,
  role: "user"
}] | selectFromArray({"role": "admin", "age": 30}) | dump }}
```

Possibly at that point it's complicated enough that you should be doing the filtering within the javascript code instead of the templating code though?

Also, possibly, given that nunjucks already has `select` and `selectattr` methods, we should follow that convention and drop `fromArray` and instead add something to differentiate it from the other two methods?

Maybe `selectAttrWithValue(attr: "role", value: "admin")` ?

**Comment by paulrobertlloyd** [comment]
**Decision:** Use keyword arguments (this is the convention used and [recommended by Nunjucks](https://mozilla.github.io/nunjucks/api#keyword-default-arguments)).

Have opened PRs for the 2 filters that have options but don’t use keyword arguments, and updated the proposed `currency` filter to use keyword arguments as well.
