### ISSUE TITLE
Add `includes` filter

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-prototype-filters#22]
Is it worth adding an 'includes' filter for arrays (which just uses the native javascript function)?

See https://github.com/DFE-Digital/manage-teacher-training-applications-prototype/pull/681

**Comment by frankieroberto** [comment]
@paulrobertlloyd any thoughts?

**Comment by paulrobertlloyd** [comment]
This is a filter I’ve used a few times myself, so definitely worth inclusion (bom-tish).

My only question is around strings; there’s an `includes` method on both [`Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) and [`String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes).

Do we want to restrict this filter to arrays (in which case should it be called `arrayIncludes`?) or only allow it on both arrays and strings (and perhaps throw error if the wrong data type provided)?

**Comment by frankieroberto** [comment]
> Do we want to restrict this filter to arrays (in which case should it be called `arrayIncludes`?) or only allow it on both arrays and strings (and perhaps throw error if the wrong data type provided)?

Ooh I didn't know about the string one. Never used that, but I can see how it might be useful. Makes sense to allow that too I think?  (Basically we'll end up exposing all the native array and string functions as filters... 😂 )

**Comment by paulrobertlloyd** [comment]
Yeah, I think so. Not sure which groups this sits in (Array filters, I guess) - this is where the grouping breaks down. Also wonder if you’d need to check that input is an Array or String. Feel free to raise a PR.
