### ISSUE TITLE
RFC: Rename filters that use the `govuk` namespace

### ISSUE THREAD

**Issue by paulrobertlloyd** [x-govuk/govuk-prototype-filters#31]
There’s a possibility of this plugin being listed as a recommendation in the Prototype Kit, but this is blocked by the fact that some filters start with `govuk`, putting them in direct conflict with future components that could be added to the design system[^1].

The following filters use `govuk`:

* `govukDate`
* `govukTime`
* `govukMarkdown`

It’s very easy to envisage the first 2 becoming components at some point, although currently the closest is called `govukDateInput`, so would a time input be called `govukTimeInput`?

Anyway, perhaps it’s best not to overload this namespace with things that are not from the design system. Alternatives:

1. `isGovukDate`, `isGovukTime`, `isGovukMarkdown`
2. `asGovukDate`, `asGovukTime`, `asGovukMarkdown`
3. `useGovukDate`, `useGovukTime`, `useGovukMarkdown`
4. `formatGovukDate`, `formatGovukTime`, `formatGovukMarkdown`
5. `date("govuk")`, `time("govuk")`, `markdown("govuk")`
6. `date({ format: "govuk" })`, `time({ format: "govuk" })`, `markdown({ format: "govuk" })`

(Using attributes seems prone to error and conflict with any existing filters). 

And for the Markdown filter:

7. `prose` 
8. `govspeak`

We could add aliases to the new filter names in 1.x version and provide a deprecation notice (somehow), before removing the `govuk` prefixed filter names in 2.x.

[^1]: There’s also a suggestion that all filters provided by plugins should use their own namespace to prevent conflicts between filters provided by separate plugins and/or prototypes, but I’m inclined to think that this may be overthinking the issue, and something that could potentially be addressed in other ways.

**Comment by frankieroberto** [comment]
I vote for number 4. The `format` prefix helps make clear what it does.

That said, arguably the time and date formats aren't exclusive to GOV.UK, so maybe they could just be `formatDate` and `formatTime`?

The markdown one is pretty govuk-specific though, as that sticks all the govuk classes in it.

**Comment by paulrobertlloyd** [comment]
> The time and date formats aren't exclusive to GOV.UK

Yes, but they are formatted to follow the GOV.UK Style Guide.

**Comment by frankieroberto** [comment]
> > The time and date formats aren't exclusive to GOV.UK
> 
> Yes, but they are formatted to follow the GOV.UK Style Guide.

True, and maybe it’s reassuring to people to see `govuk` in the filter name... 😄 

Either way is fine with me.

**Comment by frankieroberto** [comment]
I think we should close this for now, seeing as the original impetus for this (the possibility of this plugin being listed as a recommendation in the Prototype Kit) has gone.

**Comment by paulrobertlloyd** [comment]
Had the same thought as you at the weekend; seems like premature optimisation, and yes, no longer a pressing issue.
