### ISSUE TITLE
Tests broken after latest dependency update

### ISSUE THREAD

**Issue by rosado** [x-govuk/govuk-prototype-filters#85]
After latest [commit](https://github.com/x-govuk/govuk-prototype-filters/commit/78400eefc005f1407ac5f04f7ff69939cb3cfcd6) the tests are broken. After looking at the failed tests output, it's most likely due to marked version bump. Wouldn't that be enough of a reason to revet that change?

**Comment by paulrobertlloyd** [comment]
Thanks for the report, I'll take a look this weekend.

**Comment by paulrobertlloyd** [comment]
It seems that v14 removed its old renderer API, that was deprecated in v13. Have released [a new version of `govuk-markdown`](https://github.com/x-govuk/govuk-markdown/releases/tag/v0.8.0), and will push a release of this project that upgrades that dependency (see 257a088bfa10ec6c18a4652b3c0a93742e641068).

**Comment by paulrobertlloyd** [comment]
Released v1.4.2; let me know if this still causes issues.
