### ISSUE TITLE
Truncated date is using "Sept" instead of "Sep" for September

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-prototype-filters#87]
For some reason, September is getting truncated as "Sept" instead of "Sep":

```
{{ "2024-09-01" | govukDate("truncate") }}
```

> 1 Sept 2024

All the other months are truncated to their 3-letter form, which seems more expected?

Not sure why this happens - will need to dig into the Luxon docs to find out...

**Comment by frankieroberto** [comment]
@paulrobertlloyd I just had a quick peek into the rabbit hole trying to trace this, but then backed out when I got as far as trying to read the [Intl.DateTimeFormat spec](https://tc39.es/ecma402/#datetimeformat-objects) so might have to come back to this later, unless you have any ideas?

**Comment by paulrobertlloyd** [comment]
Abbreviation is based on the `en-GB` locale, and I guess whatever TC39 have deemed to be the correct month name abbreviations for that locale.

We could special case it, but doesn't look like there's any specific recommendations around abbreviating months in the GOV.UK style guide.

**Comment by frankieroberto** [comment]
@paulrobertlloyd weirdly I can't repeat it in a browser using this:

```
const df = new Intl.DateTimeFormat('en-GB', {day: "numeric", month: "short", year: "numeric"})
df.format(new Date())
```

...that returns "18 Sep 2024"

The GOV.UK style guide doesn't spell out all the months, but at least _implies_ 3 letters:

> when space is an issue - in tables or publication titles, for example - you can use truncated months: Jan, Feb

having 1 out the 12 months contain an extra letter feels unexpected?

**Comment by paulrobertlloyd** [comment]
Who knows what Luxon is doing behind the scenes? I've been thinking of using `Intl.DateTime` directly, and removing the Luxon dependency entirely, if possible. Perhaps this is another reason to do so.

**Comment by paulrobertlloyd** [comment]
Intersting:

```
const df = new Intl.DateTimeFormat('en-GB', {
  day: 'numeric',
  month: 'short',
  year: 'numeric'
}).format(new Date())
console.log(df)
```

In a browser, this returns `21 Sep 2024`, but on Node (18 and 22), it outputs `21 Sept 2024`. So this is a Node.js thing, and where it’s sourcing its localisations from. FFS.

**Comment by paulrobertlloyd** [comment]
Deno (v1.46.3) does the same thing. This must be emerging from the depths of the ICU localisation data these runtimes use, which doesn’t match with that used by browsers.

Hate to say it, but think I’ll have to special case `Sept` to remove the `t`.

**Comment by paulrobertlloyd** [comment]
Similar issue reported on Node.js in 2021, but regarding `en-AU` date format: https://github.com/nodejs/node/issues/40710
