### ISSUE TITLE
Add help text to explain what dump does

### ISSUE THREAD

**Issue by benjystanton** [x-govuk/govuk-prototype-filters#92]
The built in Nunjucks filter [dump](https://mozilla.github.io/nunjucks/templating.html#dump) is used in a couple of places…

- [Object filters](https://x-govuk.github.io/govuk-prototype-filters/object/)
- [Array filters](https://x-govuk.github.io/govuk-prototype-filters/array/)

As someone new to filters I didn't realise what dump did.

Perhaps some help text would be good to explain what it's for (i.e. debugging) and that it's safe to remove if you don't need it.

**Comment by paulrobertlloyd** [comment]
@benjystanton Ah, that’s a useful insight. Have updated the docs where `dump` is used, lemme know if this works.

**Comment by benjystanton** [comment]
Yeah that's great. Thanks!
